version: '3.8'
services:
  automaks:
    image: registry.digitalocean.com/magnus-images/other:automaks-1.0.0
    container_name: automaks
    restart: unless-stopped
    networks:
      - automaks

networks:
  automaks:
    name: automaks
    driver: bridge
